### ISSUE TITLE
Launching the program from the start menu causes file server to fail

### ISSUE THREAD

**Issue by WhatSkill** [l3lackShark/gosumemory#24] opened 2020-08-31 03:34 UTC
I could originally access the link for the counter but now it wont let me any solutions? thanks

**Comment by l3lackShark** [comment] 2020-08-31 10:21
Need more context. Is the game running?  Any error messages?

**Comment by mnyui** [comment] 2020-09-05 15:13
i also have this issue. to answer your question
the game is running and there seems to be no error messages on the gosumemory.exe when running
when using http://localhost:24050/, it says 404 page not found.
http://localhost:24050/json works tho

**Comment by l3lackShark** [comment] 2020-09-05 15:29
Is the `static` directory present in the same folder as the program?

**Comment by mnyui** [comment] 2020-09-05 15:31
yessir

**Comment by l3lackShark** [comment] 2020-09-05 16:05
Have a screenshot or a video of the whole initialization and attempt to load the `/` endpoint?

**Comment by l3lackShark** [comment] 2020-09-05 16:10
It would be really nice if you could join our discord server and screen share me the issue. I've seen this several times but cannot reproduce myself.

**Comment by Gadzza** [comment] 2020-09-08 08:44
You can reinstall the app. Delete everything in the folder and reextract. That worked for me. I don't know what caused that. What i did was a modify in css and a restart of the app. Maybe modifying while the app is running can cause this?

**Comment by Gadzza** [comment] 2020-09-08 09:30
@l3lackShark I just found out what the problem is. If you run gosumemory from windows search bar it doesn't work. At least everytime i tryied and gave the error it was from windows search bar, BUT if i run it from the folder it doesn't has a problem.

**Comment by l3lackShark** [comment] 2020-09-08 15:44
Could very well be out of scope golang issue. I'll look into it, thanks for the steps of reproduction.

**Comment by l3lackShark** [comment] 2020-09-08 16:37
LOL, the only thing I can say right now. I have no words. 
![image](https://user-images.githubusercontent.com/20248967/92503982-76d60e00-f21b-11ea-81ce-1415c415792b.png)

**Comment by l3lackShark** [comment] 2020-09-08 16:46
4ab70eb6cd7429f383cc17b6b458ec1c846885d6 Should be fixed in the next release. In the meantime please pin the program to your panel or launch from the folder directly.

**Closed by l3lackShark** 2020-09-08 16:46 UTC
Labels: bug
