### ISSUE TITLE
Empty mods string on mirror mod

### ISSUE THREAD

**Issue by TheEZIC** [l3lackShark/gosumemory#22] opened 2020-08-29 11:33 UTC
![image](https://user-images.githubusercontent.com/35061249/91635863-8a57cc80-ea04-11ea-815d-138b5205ecc7.png)

**Comment by TheEZIC** [comment] 2020-08-29 11:41
And when they active hit counts always 0.

**Comment by l3lackShark** [comment] 2020-08-29 11:44
hit counts you mean like 300,100,50, etc? If so, then it means that the offset is different for those. Not sure if I want to do that. But the empty string bug should be fairly easy to fix.

**Comment by TheEZIC** [comment] 2020-08-29 11:54
It's not a problem with offset (I never change it), couse while Mirror mod active, hit counts (300,100,50, etc) always zero

**Comment by l3lackShark** [comment] 2020-08-29 15:06
Initial problem is now fixed via faf35c85f984d1b34e21072a26fc0be4bae1e47e, not sure if I wanna touch memory offsets just to get the mirror mod right.

**Comment by l3lackShark** [comment] 2020-08-29 15:15
Upon closer look It seems that it works? Can you elaborate more on your issue? (this play was done with the Mirror mod)
![image](https://user-images.githubusercontent.com/20248967/91640067-657b4d80-ea34-11ea-92b4-34304f728afd.png)

**Comment by TheEZIC** [comment] 2020-08-29 15:18
![image](https://user-images.githubusercontent.com/35061249/91640118-e0883800-ea23-11ea-84bb-34ad3719e264.png)
Hm....I started playing new song but I have hit counts from previous one.

**Comment by l3lackShark** [comment] 2020-08-29 15:20
Can't reproduce. Will reopen if you can provide explicit steps of reproduction. (video, preferably)

**Closed by l3lackShark** 2020-08-29 15:20 UTC
